defaults:
  - fcp/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 2e6
PARTNER_POP_SIZE: 23 # true partner pop size is PARTNER_POP_SIZE * NUM_CHECKPOINTS
LR: .0001
NUM_ENVS: 8
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 16
CLIP_EPS: 0.3
ENT_COEF: 0.01
ego_train_algorithm: 
  TOTAL_TIMESTEPS: 3e7
  LR: 1e-4
  ENT_COEF: 0.01
  CLIP_EPS: 0.05

