defaults:
  - task: lbf # task configs
  - global_heldout_settings # global settings for heldout evaluation
  - hydra: hydra_simple
  - _self_

ENV_NAME: ${task.ENV_NAME}
ENV_KWARGS: ${task.ENV_KWARGS}
TASK_NAME: ${task.TASK_NAME}

label: ""
name: ${TASK_NAME}/heldout_ego_eval/${label}

ego_agent:
  # provide any necessary args to initialize the agent here
  # ex) S5_ACTOR_CRITIC_HIDDEN_DIM: 64
  # defaults for each actor type will be used if no args are provided
  # overcooked test policy
  # path: results/overcooked-v1/cramped_room/brdiv/2025-04-16/13-53-06/saved_train_run
  # actor_type: actor_with_conditional_critic
  # idx_list: [[0, -1], [1, -1]]
  # ckpt_key: final_params_conf
  # POP_SIZE: 4
  # lbf test policy
  path: results_explore/lbf/fcp_s5/2025-04-13_18-42-46/saved_train_run
  actor_type: s5
  idx_list: [[0, -1]] # list of seed and checkpoint index to evaluate. If null, all checkpoints will be loaded.
  test_mode: true