defaults:
  - _self_         # Ensures that values in this file override imported ones if needed

ENV_NAME: lbf
ROLLOUT_LENGTH: 128 # rollout length must be greater than episode length
ENV_KWARGS: {}

TOTAL_TIMESTEPS: 5e5
ACTOR_TYPE: mlp
SEED: 12345
LR: .0001
NUM_ENVS: 8
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 4
NUM_CHECKPOINTS: 5
NUM_SEEDS: 3
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.03
ENT_COEF: 0.01
VF_COEF: 1.0
MAX_GRAD_NORM: 1.0
ANNEAL_LR: True

# WandB Params
logger: 
  project: open-ended-aht
  entity: aht-project
  tags: 
    - ippo
    - "${ENV_NAME}"
  mode: offline # options: online, offline, disabled
  verbose: false
  log_train_out: false # whether to log the out dictionary

local_logger:
  save_figures: true  
  save_train_out: false

hydra:
  job:
    name: ippo
    chdir: true
  run:
    dir: results/${ENV_NAME}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
