defaults:
  - open_ended_lagrange/_base_
  - _self_ # values from this file override the values from the base file

TIMESTEPS_PER_ITER_PARTNER: 8e7 # per iter of open-ended training, divided between conf-br and conf-ego and between all partner seeds
TIMESTEPS_PER_ITER_EGO: 3e6
NUM_OPEN_ENDED_ITERS: 20
LOWER_REGRET_THRESHOLD_START: 0.0
LOWER_REGRET_THRESHOLD_END: 0.0
UPPER_REGRET_THRESHOLD_START: 60.0
UPPER_REGRET_THRESHOLD_END: 60.0
LAGRANGE_MULTIPLIER_LR: 0.01
LR: 1e-3
NUM_MINIBATCHES: 8
CLIP_EPS: 0.1
ENT_COEF: 0.05
ANNEAL_LR: false
EGO_ARGS:
  LR: 3e-5
  ENT_COEF: .001
  CLIP_EPS: 0.1
  UPDATE_EPOCHS: 10
  S5_D_MODEL: 128
  S5_SSM_SIZE: 128
  S5_ACTOR_CRITIC_HIDDEN_DIM: 1024
  FC_N_LAYERS: 3
