ENV_NAME: overcooked-v1
ROLLOUT_LENGTH: 400
ENV_KWARGS:
  layout: cramped_room
  random_obj_state: true
  do_reward_shaping: true
  reward_shaping_params:
    PLACEMENT_IN_POT_REW: .5 # reward for putting ingredients 
    PLATE_PICKUP_REWARD: .1 # reward for picking up a plate
    SOUP_PICKUP_REWARD: 1. # reward for picking up a ready soup
    ONION_PICKUP_REWARD: .1
    COUNTER_PICKUP_REWARD: 0
    COUNTER_DROP_REWARD: 0
TASK_NAME: overcooked-v1/cramped_room
