defaults:
  - brdiv/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 4.5e7
PARTNER_POP_SIZE: 4
NUM_ENVS: 64
# SP weight = 1 + 2*XP weight. 
# Thus, as XP weight -> 0, SP/(SP+XP) -> 1.
# If XP weight -> infinity, XP/(SP+XP) -> 1/3, and SP/(SP+XP) -> 2/3.
XP_LOSS_WEIGHTS: 0.5 # 10
LR: 1e-4
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 16
CLIP_EPS: 0.05
ENT_COEF: 0.01
ego_train_algorithm: 
  TOTAL_TIMESTEPS: 3e7
  LR: 1e-4
  ENT_COEF: 0.01
  CLIP_EPS: 0.05