ENV_NAME: overcooked-v1
ROLLOUT_LENGTH: 400 # rollout length must be greater than episode length
ENV_KWARGS:
  layout: asymm_advantages
  random_obj_state: true
TASK_NAME: overcooked-v1/asymm_advantages
