defaults:
  - comedi/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 1e7
PARTNER_POP_SIZE: 10
LR: 5e-4
UPDATE_EPOCHS: 15
CLIP_EPS: 0.05
ENT_COEF: 0.01