defaults:
  - open_ended_lagrange/_base_
  - _self_ # values from this file override the values from the base file

TIMESTEPS_PER_ITER_PARTNER: 4e6 # per iter of open-ended training, divided between conf-br and conf-ego and between all partner seeds
TIMESTEPS_PER_ITER_EGO: 1e6
NUM_OPEN_ENDED_ITERS: 30

LOWER_REGRET_THRESHOLD_START: 0.0 # min regret is 0.0 - 0.5 = -0.5
LOWER_REGRET_THRESHOLD_END: 0.0
UPPER_REGRET_THRESHOLD_START: 0.2 # max regret is 0.5 - 0.0 = 0.5
UPPER_REGRET_THRESHOLD_END: 0.2
# LOWER_REGRET_THRESHOLD_START: -0.5 # 0.0 # min regret is 0.0 - 0.5 = -0.5
# LOWER_REGRET_THRESHOLD_END: 0.0 # 0.0
# UPPER_REGRET_THRESHOLD_START: 0.5 # 0.2 # max regret is 0.5 - 0.0 = 0.5
# UPPER_REGRET_THRESHOLD_END: 0.2 # 0.2
LAGRANGE_MULTIPLIER_LR: 0.01
LR: 1e-3
CLIP_EPS: 0.1
ENT_COEF: 0.001
ANNEAL_LR: true
EGO_ARGS:
  LR: 5e-5
  ENT_COEF: 1e-4
  CLIP_EPS: 0.1
  ANNEAL_LR: false
  UPDATE_EPOCHS: 10
  S5_D_MODEL: 128
  S5_SSM_SIZE: 128
  S5_ACTOR_CRITIC_HIDDEN_DIM: 1024
  FC_N_LAYERS: 3