defaults:
  - open_ended_minimax/_base_
  - _self_ # values from this file override the values from the base file

TIMESTEPS_PER_ITER_PARTNER: 1.6e7 # per iter of open-ended training, divided between all partner seeds
TIMESTEPS_PER_ITER_EGO: 6e6
NUM_OPEN_ENDED_ITERS: 20
LR: 1e-3
NUM_MINIBATCHES: 8
CLIP_EPS: 0.1
ENT_COEF: 0.05
ANNEAL_LR: false
EGO_ARGS:
  LR: 1e-5
  ENT_COEF: 1e-4
  CLIP_EPS: 0.1
  UPDATE_EPOCHS: 5
  S5_D_MODEL: 128
  S5_SSM_SIZE: 128
  S5_ACTOR_CRITIC_HIDDEN_DIM: 1024
  FC_N_LAYERS: 3
