defaults:
  - ippo/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 1e5
SEED: 12345
LR: 0.0003
NUM_ENVS: 16
UPDATE_EPOCHS: 10
NUM_MINIBATCHES: 4
CLIP_EPS: 0.2
ENT_COEF: 0.01
